version: '3.4'

services:
  itemservice:
    image: itemservice:dev
    container_name: ItemService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ItemService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_itemservice$
    volumes:
      - D:\Dotnet\Material\DEVOPS\Docker\DockerHandsOn\DockerComposeDemo\ItemService:/app
      - D:\Dotnet\Material\DEVOPS\Docker\DockerHandsOn\DockerComposeDemo:/src
      - C:\Users\SANTHOSH\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_itemservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_itemservice$ \"/app/bin/Debug/netcoreapp3.0/ItemService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  productservice:
    image: productservice:dev
    container_name: ProductService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ProductService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_productservice$
    volumes:
      - D:\Dotnet\Material\DEVOPS\Docker\DockerHandsOn\DockerComposeDemo\ProductService:/app
      - D:\Dotnet\Material\DEVOPS\Docker\DockerHandsOn\DockerComposeDemo:/src
      - C:\Users\SANTHOSH\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_productservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_productservice$ \"/app/bin/Debug/netcoreapp3.0/ProductService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
