apiVersion: v1
kind: Pod
metadata:
  name: hello-pod1
  labels:
    name: hello-pod1
spec:
  containers:
  - name: hello-container
    image: hello-world:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
   
