apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: default
  labels:
    app: nginxapp
spec:
  containers:
  - name: ng-container1
    image: nginx:latest
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
   