version: '3.4'

services:
  dockertestapp1:
    image: dockertestapp1:dev
    container_name: DockerTestApp1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DockerTestApp1"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dockertestapp1$
    volumes:
      - D:\Dotnet\Material\DEVOPS\Docker\DockerHandsOn\DockerTestApp1\DockerTestApp1:/app
      - D:\Dotnet\Material\DEVOPS\Docker\DockerHandsOn\DockerTestApp1:/src
      - C:\Users\SANTHOSH\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dockertestapp1$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dockertestapp1$ \"/app/bin/Debug/netcoreapp3.1/DockerTestApp1.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true